/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4b71827e-3303-4524-9e7b-33c1622a0634",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FrnURgWxl",
    "aws_user_pools_web_client_id": "3eo6066r2qfh5jio28a5hl9h1h",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "bbldelivery",
            "endpoint": "https://jzi3io77oj.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
